version: 2

sources:
  - name: bronze
    database: streamline
    schema: |
      {{ "COSMOS_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "COSMOS" }}
    tables:
      - name: blocks
      - name: transactions
        identifier: tx_search
      - name: validators
      - name: blockchain
  - name: osmo
    database: osmosis
    schema: silver
    tables: 
      - name: asset_metadata
  - name: bronze_api
    schema: bronze_api
    tables: 
      - name: blockchain
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'COSMOS' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: number_sequence
