version: 2

sources:
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "COSMOS_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "COSMOS" }}
    tables:
      - name: blocks
      - name: tx_search
      - name: validators
  - name: osmo
    database: osmosis
    schema: silver
    tables: 
      - name: asset_metadata
