version: 2

sources:
  - name: bronze
    database: streamline
    schema: |
      {{ "COSMOS_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "COSMOS" }}
    tables:
      # - name: blocks
      # - name: transactions
      #   identifier: tx_search
      # - name: validators
      - name: blockchain
      - name: blocks_ch1
        identifier: migrated_blocks_ch1
      - name: tx_search_ch1
        identifier: migrated_tx_search_ch1
      - name: blocks_ch2
        identifier: migrated_blocks_ch2
      - name: tx_search_ch2
        identifier: migrated_tx_search_ch2
      - name: blocks_ch3
        identifier: migrated_blocks_ch3
      - name: tx_search_ch3
        identifier: migrated_tx_search_ch3
      - name: blocks_v2
      - name: txcount_v2
      - name: transactions_v2
      
  - name: osmo
    database: osmosis
    schema: silver
    tables: 
      - name: asset_metadata
  - name: bronze_api
    schema: bronze_api
    tables: 
      - name: blockchain
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'COSMOS' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: number_sequence
      - name: labels_combined
      - name: hourly_prices_coin_gecko
  - name: github_actions
    database: cosmos
    schema: github_actions
    tables:
      - name: workflows